version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: interviewbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: interview-qdrant
    ports:
      - "6334:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  embedding-service:
    build:
      context: ./embedding-service
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  qdrant_storage: