name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: coral-rider-464414-e1
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry or GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/YOUR_PROJECT_ID/my-fullstack-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/coral-rider-464414-e1/my-fullstack-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-fullstack-app \
            --image gcr.io/coral-rider-464414-e1/my-fullstack-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
