spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/interviewbot
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

gemini:
  api-key: AIzaSyCMYYeQQPy7o2hd79cKi-App4YOuuqY5XY
  endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
qdrant:
  host: http://localhost:6334
