name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Firebase service account file
        env:
          FIREBASE_SERVICE_ACCOUNT_B64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_B64 }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT_B64 | base64 --decode > key.json 

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: coral-rider-464414-e1

      - name: Configure Docker for Artifact Registry or GCR
        run: gcloud auth configure-docker


      - name: Build Docker image
        env:
          REACT_APP_GEMINI_API_KEY: ${{ secrets.REACT_APP_GEMINI_API_KEY }}
        run: |
          docker build --build-arg REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY} -t gcr.io/coral-rider-464414-e1/my-fullstack-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/coral-rider-464414-e1/my-fullstack-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-fullstack-app \
            --image gcr.io/coral-rider-464414-e1/my-fullstack-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_ENDPOINT=${{ secrets.GEMINI_ENDPOINT }}"
