name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Аутентификация через сервисный аккаунт (JSON в секрете GCP_SA_KEY)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ✅ Установка gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: coral-rider-464414-e1
          install_components: docker

      - name: Configure Docker for Artifact Registry or GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/coral-rider-464414-e1/my-fullstack-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/coral-rider-464414-e1/my-fullstack-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-fullstack-app \
            --image gcr.io/coral-rider-464414-e1/my-fullstack-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
